### ISSUE TITLE
Listening with linux mode

### ISSUE THREAD

**Issue by sbnair** [Christophe-Foyer/IRIS-Voice-Recognition#1] opened 2017-01-11 14:31 UTC
Hi

   I have installed all the dependencies in raspberry pi 3 and then started to run voice.py in the terminal , it is continuously printing listening with linux mode.I have speaker and microphone, please let me know what i need to do, i am speaking but nothing is showing in the screen except the message is continuously displayed.

Thanks,
Shaliesh.

**Comment by Christophe-Foyer** [comment] 2017-01-11 14:58
Hi Shaliesh!

I had the same issue last time I did a fresh install and I probably forgot a step in the installation (which I should probably write better instructions for). Are you using alsa? If so try opening the alsa mixer ("alsamixer" in the terminal) and making sure you've selected the right input device for your microphone. Then make sure it works by recording some audio (use arecord, not sure what the parameters are but I can help you out more when I get access to my computer in a couple hours) and play it. If it works try running the script and hopefully it can tell you the time or something.

Best,

Christophe

EDIT: Ok, here's a couple things I'd like you to try (assuming you're using alsa for audio control, I think that's standard on raspbian, I've only tested this on OSMC, it's not quite as polished as it could be, but once you get it to work you can do a lot of cool stuff very easily)
Start by typing:
`alsamixer`
This will open up the alsa mixer. Make sure your microphone is your primary input device, once that's done, input this command: 
`arecord -d test.wav`
Speak a little then close it with control+c (not best practice but that's ok, we'll be deleting the file anyways). Once that's done, you want to make sure you can hear what your microphone recorded:
`aplay test.wav`
If you hear yourself, try the script, otherwise we can look for another solution. You probably want to delete your test audio afterwards too:
`rm test.wav`
(note: you might need to type sudo before these commands to execute them as superuser)

**Comment by sbnair** [comment] 2017-01-12 04:59
Hi Christophe

      Thanks for the reply, i have tried with alsamixer and i am able to record my voice and also hear it using play, no problem in that.

       When i try with voice.py i am able to hear initial voice from the software saying the version number and then it shows listening with linux mode but after that this message is repeating continuously.please let me know what i need to do.

Thanks,
Shailesh.

**Comment by Christophe-Foyer** [comment] 2017-01-12 07:50
Ah, I think I might know what the issue is. If you look at this line in voice.py:
'with sr.Microphone(device_index = 1, sample_rate = 44100, chunk_size = 4096) as source' on line 283
It asks for the device index which might not be the same on your setup. Try using the device ID used by alsa.I'll have to make that configurable whether that's your problem or not since that's definitely not going to be the same for everyone.
What's weird is it's not saying the initialization greeting line but it is saying the version number. Not sure what that's about. I'll look into it.

**Comment by sbnair** [comment] 2017-01-12 11:12
I changed the device based on what i got by typing the lsusb command 

BUS 001 Device 005: ID 4555:1031, out of that i took 1031 which is the device id and replaced instead of 1 but there is no change in the functionality, anyways i am giving you the log :

  Only tested on Raspberry pi boards...
executing command: cd /home/pi/Documents/IRISVoiceRecognition
Initializing Iris version 2 point 1 point 1
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.20.1; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Playing MPEG stream 1 of 1: tts.mp3 ...

MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono

[0:03] Decoding of tts.mp3 finished.
listening with linux mode
listening with linux mode
listening with linux mode
Playing WAVE 'message.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
listening with linux mode
listening with linux mode
/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py:30: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
listening with linux mode
listening with linux mode

Please let me know if you get any idea.

Thanks.

**Comment by Christophe-Foyer** [comment] 2017-01-12 18:48
Ok, I just updated voice.py so it should use the default microphone instead of having to specify which one, you could just delete the arguments for sr.microphone(%contents%) if you want to do it manually, or you can also download the new file (you'll have to add your wolframalpha API ID in the user variables since I removed mine which I forgot was in there, you only get so many hits per month for free and I can't be sharing it with too many people, they're free though so it's easy to get your own). The new file also outputs a few more things which will make it easier to debug.
Hope it works this time.

Best,
Christophe

**Comment by sbnair** [comment] 2017-01-13 15:21
Thanks for giving me the updated code, after having the new version of voice.py i didn't see any change but after restarting the computer and then checked the voice.py i am getting this error which is different which is giving repeated welcome voice, now the error is in 619 line related to chatterbot in voice.py, i have changed the wolframalpha API ID to mine but still i get this error :

      Only tested on Raspberry pi boards...
executing command: cd /home/pi/Documents/IRISVoiceRecognition
Initializing Iris version 2 point 1 point 1
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.20.1; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Playing MPEG stream 1 of 1: tts.mp3 ...

MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono

[0:03] Decoding of tts.mp3 finished.

Initializing Iris version 2 point 1 point 1
/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py:30: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Playing WAVE 'message.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.20.1; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Playing MPEG stream 1 of 1: tts.mp3 ...

MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono
[nltk_data] Downloading package stopwords to /home/pi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/pi/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/pi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /home/pi/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "voice.py", line 619, in chatbotStart
    chatbot.train("chatterbot.corpus.english.conversations")
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 117, in train
    trainer.train(pair)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py", line 46, in find
    values = self.database.data(key=statement_text)
  File "/usr/local/lib/python2.7/dist-packages/jsondb/db.py", line 98, in data
    return self._get_content(key)
  File "/usr/local/lib/python2.7/dist-packages/jsondb/db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "/usr/local/lib/python2.7/dist-packages/jsondb/file_writer.py", line 15, in read_data
    obj = decode(content)
  File "/usr/local/lib/python2.7/dist-packages/jsondb/compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 3 - line 1 column 15769 (char 2 - 15768)


[0:03] Decoding of tts.mp3 finished.
[nltk_data] Downloading package stopwords to /home/pi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/pi/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /home/pi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

**Comment by Christophe-Foyer** [comment] 2017-01-13 18:20
[voice.zip](https://github.com/Christophe-Foyer/IRIS-Voice-Recognition/files/705039/voice.zip)

hmm, is your wolframalpha appID of the form EZ36R-7RX9J8B39H (not an actual app ID). You also kept the apostrophes when inputing it right?

If you want I can give you a version without the chatterbot if you just want something that works. Otherwise if you just want something that listens to audio through your microphone and outputs a string you can literally copy the "listen" function in the code and that outputs as a string what google thinks is the most likely interpretation of what you said. Sorry for the slightly buggy setup process, this code definitely can work, it just hasn't been tested on any other systems than our initial pi setup. Are you trying to use it as-is or integrate it into another project? If you want to just use it, I might suggest other projects such as Jasper (I think that's what it's called) or Amazon Echo on your Pi. Otherwise if you want to integrate it, you can definitely copy the listen function (that's really the important part of this script) and any other function you want. I'll still try to fix it for you, but I might need to test it on the Pi that was exhibiting the same behavior (which I'm not sure I fixed yet) which I'll only have access to next week.

Just tell me if you want me to trim the chatterbot from the script (which is really not that useful and seems to be causing some kind of bug...)

Sorry for the buggy script, never really expected anyone ever trying to use it as-is, feel free to use any part of it though.

EDIT: attached a version of voice.py without the chatterbot, try it with that (you can name the file whatever you want by the way, for example "voice-nochatter.py" if you want to keep multiple versions, just make sure it's in the same folder as the rest of the stuff and you run it using the name of the version you want to use)
EDIT2: also I can't test any of this because I don't have my pi with me, I'll be back home in a few days though, I can definitely debug better then

**Comment by sbnair** [comment] 2017-01-14 11:31
Thanks for sending me the new change but it is giving some errors when i compile, anyways i will try to fix it and the appid is of the form that you send me and also have kept the apostrophes.

I have tried jasper, jarvis, etc and some other scripts available but those all are depending on google voice translation or some other providers like amazon, would like to make the speech to text and text to speech conversion in offline mode as possible.My aim to make a talking assistant in raspberry pi 3 which can talk to me when i am walking, driving and cycling.Anyways i will also try to contribute to this code in my free time.

Thanks.

**Comment by Christophe-Foyer** [comment] 2017-01-14 11:51
Gotcha, this code doesn't work offline either, it uses google voice (could also be modified to use other APIs though). Full voice recognition might just be too complicated to do offline on a pi, but maybe there's some code somewhere that can listen for a few keywords.
I'll try and fix it anyways when I get back. Thanks for the feedback and helping me debug.
Best,
Christophe

**Closed as completed** 2017-01-14 17:11 UTC
